<?php
/**
 * @file
 * novo_content_feature.features.user_permission.inc
 */

/**
 * Implements hook_user_default_permissions().
 */
function novo_content_feature_user_default_permissions() {
  $permissions = array();

  // Exported permission: 'create field_app7_statement_agree'.
  $permissions['create field_app7_statement_agree'] = array(
    'name' => 'create field_app7_statement_agree',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_app_7_final_agree_1'.
  $permissions['create field_app_7_final_agree_1'] = array(
    'name' => 'create field_app_7_final_agree_1',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_app_7_final_agree_2'.
  $permissions['create field_app_7_final_agree_2'] = array(
    'name' => 'create field_app_7_final_agree_2',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_app_7_final_agree_3'.
  $permissions['create field_app_7_final_agree_3'] = array(
    'name' => 'create field_app_7_final_agree_3',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_app_7_final_agree_4'.
  $permissions['create field_app_7_final_agree_4'] = array(
    'name' => 'create field_app_7_final_agree_4',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_app_7_final_agree_5'.
  $permissions['create field_app_7_final_agree_5'] = array(
    'name' => 'create field_app_7_final_agree_5',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_app_7_final_agree_6'.
  $permissions['create field_app_7_final_agree_6'] = array(
    'name' => 'create field_app_7_final_agree_6',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_app_status'.
  $permissions['create field_app_status'] = array(
    'name' => 'create field_app_status',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_app_user'.
  $permissions['create field_app_user'] = array(
    'name' => 'create field_app_user',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_beliefs2_q1'.
  $permissions['create field_beliefs2_q1'] = array(
    'name' => 'create field_beliefs2_q1',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_beliefs2_q2'.
  $permissions['create field_beliefs2_q2'] = array(
    'name' => 'create field_beliefs2_q2',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_beliefs2_q3'.
  $permissions['create field_beliefs2_q3'] = array(
    'name' => 'create field_beliefs2_q3',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_beliefs_q1'.
  $permissions['create field_beliefs_q1'] = array(
    'name' => 'create field_beliefs_q1',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_beliefs_q2'.
  $permissions['create field_beliefs_q2'] = array(
    'name' => 'create field_beliefs_q2',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_beliefs_q3'.
  $permissions['create field_beliefs_q3'] = array(
    'name' => 'create field_beliefs_q3',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_beliefs_q4'.
  $permissions['create field_beliefs_q4'] = array(
    'name' => 'create field_beliefs_q4',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_beliefs_q5'.
  $permissions['create field_beliefs_q5'] = array(
    'name' => 'create field_beliefs_q5',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_beliefs_q6'.
  $permissions['create field_beliefs_q6'] = array(
    'name' => 'create field_beliefs_q6',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_beliefs_q7'.
  $permissions['create field_beliefs_q7'] = array(
    'name' => 'create field_beliefs_q7',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_church_email'.
  $permissions['create field_church_email'] = array(
    'name' => 'create field_church_email',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_church_home'.
  $permissions['create field_church_home'] = array(
    'name' => 'create field_church_home',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_church_how_long_attended'.
  $permissions['create field_church_how_long_attended'] = array(
    'name' => 'create field_church_how_long_attended',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_church_phone'.
  $permissions['create field_church_phone'] = array(
    'name' => 'create field_church_phone',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_church_prev'.
  $permissions['create field_church_prev'] = array(
    'name' => 'create field_church_prev',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_church_reference'.
  $permissions['create field_church_reference'] = array(
    'name' => 'create field_church_reference',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_color_preference'.
  $permissions['create field_color_preference'] = array(
    'name' => 'create field_color_preference',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_completed'.
  $permissions['create field_completed'] = array(
    'name' => 'create field_completed',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_email'.
  $permissions['create field_email'] = array(
    'name' => 'create field_email',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_empl_length'.
  $permissions['create field_empl_length'] = array(
    'name' => 'create field_empl_length',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_empl_title'.
  $permissions['create field_empl_title'] = array(
    'name' => 'create field_empl_title',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_employer'.
  $permissions['create field_employer'] = array(
    'name' => 'create field_employer',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_expired_date'.
  $permissions['create field_expired_date'] = array(
    'name' => 'create field_expired_date',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_faq_a'.
  $permissions['create field_faq_a'] = array(
    'name' => 'create field_faq_a',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_how_did_you_hear_about_nov'.
  $permissions['create field_how_did_you_hear_about_nov'] = array(
    'name' => 'create field_how_did_you_hear_about_nov',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ministry_cert'.
  $permissions['create field_ministry_cert'] = array(
    'name' => 'create field_ministry_cert',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ministry_experience'.
  $permissions['create field_ministry_experience'] = array(
    'name' => 'create field_ministry_experience',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_notes'.
  $permissions['create field_notes'] = array(
    'name' => 'create field_notes',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_parent_email'.
  $permissions['create field_parent_email'] = array(
    'name' => 'create field_parent_email',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_parent_guardian_first_name'.
  $permissions['create field_parent_guardian_first_name'] = array(
    'name' => 'create field_parent_guardian_first_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_parent_guardian_last_name'.
  $permissions['create field_parent_guardian_last_name'] = array(
    'name' => 'create field_parent_guardian_last_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_parent_phone'.
  $permissions['create field_parent_phone'] = array(
    'name' => 'create field_parent_phone',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_parent_prefix'.
  $permissions['create field_parent_prefix'] = array(
    'name' => 'create field_parent_prefix',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_pertinent_q1'.
  $permissions['create field_pertinent_q1'] = array(
    'name' => 'create field_pertinent_q1',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_pertinent_q10'.
  $permissions['create field_pertinent_q10'] = array(
    'name' => 'create field_pertinent_q10',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_pertinent_q11'.
  $permissions['create field_pertinent_q11'] = array(
    'name' => 'create field_pertinent_q11',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_pertinent_q12'.
  $permissions['create field_pertinent_q12'] = array(
    'name' => 'create field_pertinent_q12',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_pertinent_q13'.
  $permissions['create field_pertinent_q13'] = array(
    'name' => 'create field_pertinent_q13',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_pertinent_q2'.
  $permissions['create field_pertinent_q2'] = array(
    'name' => 'create field_pertinent_q2',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_pertinent_q3'.
  $permissions['create field_pertinent_q3'] = array(
    'name' => 'create field_pertinent_q3',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_pertinent_q4'.
  $permissions['create field_pertinent_q4'] = array(
    'name' => 'create field_pertinent_q4',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_pertinent_q5'.
  $permissions['create field_pertinent_q5'] = array(
    'name' => 'create field_pertinent_q5',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_pertinent_q6'.
  $permissions['create field_pertinent_q6'] = array(
    'name' => 'create field_pertinent_q6',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_pertinent_q7'.
  $permissions['create field_pertinent_q7'] = array(
    'name' => 'create field_pertinent_q7',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_pertinent_q8'.
  $permissions['create field_pertinent_q8'] = array(
    'name' => 'create field_pertinent_q8',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_pertinent_q9'.
  $permissions['create field_pertinent_q9'] = array(
    'name' => 'create field_pertinent_q9',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_program_policies_agree'.
  $permissions['create field_program_policies_agree'] = array(
    'name' => 'create field_program_policies_agree',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_1_email'.
  $permissions['create field_ref_1_email'] = array(
    'name' => 'create field_ref_1_email',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_1_first_name'.
  $permissions['create field_ref_1_first_name'] = array(
    'name' => 'create field_ref_1_first_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_1_how_know'.
  $permissions['create field_ref_1_how_know'] = array(
    'name' => 'create field_ref_1_how_know',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_1_how_long'.
  $permissions['create field_ref_1_how_long'] = array(
    'name' => 'create field_ref_1_how_long',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_1_how_long_period'.
  $permissions['create field_ref_1_how_long_period'] = array(
    'name' => 'create field_ref_1_how_long_period',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_1_last_name'.
  $permissions['create field_ref_1_last_name'] = array(
    'name' => 'create field_ref_1_last_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_1_phone'.
  $permissions['create field_ref_1_phone'] = array(
    'name' => 'create field_ref_1_phone',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_1_prefix'.
  $permissions['create field_ref_1_prefix'] = array(
    'name' => 'create field_ref_1_prefix',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_2_email'.
  $permissions['create field_ref_2_email'] = array(
    'name' => 'create field_ref_2_email',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_2_first_name'.
  $permissions['create field_ref_2_first_name'] = array(
    'name' => 'create field_ref_2_first_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_2_how_know'.
  $permissions['create field_ref_2_how_know'] = array(
    'name' => 'create field_ref_2_how_know',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_2_how_long'.
  $permissions['create field_ref_2_how_long'] = array(
    'name' => 'create field_ref_2_how_long',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_2_how_long_period'.
  $permissions['create field_ref_2_how_long_period'] = array(
    'name' => 'create field_ref_2_how_long_period',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_2_last_name'.
  $permissions['create field_ref_2_last_name'] = array(
    'name' => 'create field_ref_2_last_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_2_phone'.
  $permissions['create field_ref_2_phone'] = array(
    'name' => 'create field_ref_2_phone',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_2_prefix'.
  $permissions['create field_ref_2_prefix'] = array(
    'name' => 'create field_ref_2_prefix',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_3_email'.
  $permissions['create field_ref_3_email'] = array(
    'name' => 'create field_ref_3_email',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_3_first_name'.
  $permissions['create field_ref_3_first_name'] = array(
    'name' => 'create field_ref_3_first_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_3_how_know'.
  $permissions['create field_ref_3_how_know'] = array(
    'name' => 'create field_ref_3_how_know',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_3_how_long'.
  $permissions['create field_ref_3_how_long'] = array(
    'name' => 'create field_ref_3_how_long',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_3_how_long_period'.
  $permissions['create field_ref_3_how_long_period'] = array(
    'name' => 'create field_ref_3_how_long_period',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_3_last_name'.
  $permissions['create field_ref_3_last_name'] = array(
    'name' => 'create field_ref_3_last_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_3_phone'.
  $permissions['create field_ref_3_phone'] = array(
    'name' => 'create field_ref_3_phone',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ref_3_prefix'.
  $permissions['create field_ref_3_prefix'] = array(
    'name' => 'create field_ref_3_prefix',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_reference_request_1'.
  $permissions['create field_reference_request_1'] = array(
    'name' => 'create field_reference_request_1',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_reference_request_2'.
  $permissions['create field_reference_request_2'] = array(
    'name' => 'create field_reference_request_2',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_reference_request_church'.
  $permissions['create field_reference_request_church'] = array(
    'name' => 'create field_reference_request_church',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_reference_request_parents'.
  $permissions['create field_reference_request_parents'] = array(
    'name' => 'create field_reference_request_parents',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_reference_request_standby'.
  $permissions['create field_reference_request_standby'] = array(
    'name' => 'create field_reference_request_standby',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_ssn'.
  $permissions['create field_ssn'] = array(
    'name' => 'create field_ssn',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_texting'.
  $permissions['create field_texting'] = array(
    'name' => 'create field_texting',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_things_q1'.
  $permissions['create field_things_q1'] = array(
    'name' => 'create field_things_q1',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_things_q2'.
  $permissions['create field_things_q2'] = array(
    'name' => 'create field_things_q2',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_things_q3'.
  $permissions['create field_things_q3'] = array(
    'name' => 'create field_things_q3',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_things_q4'.
  $permissions['create field_things_q4'] = array(
    'name' => 'create field_things_q4',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_things_q5'.
  $permissions['create field_things_q5'] = array(
    'name' => 'create field_things_q5',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_things_q6'.
  $permissions['create field_things_q6'] = array(
    'name' => 'create field_things_q6',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_volunteer_interests_roles'.
  $permissions['create field_volunteer_interests_roles'] = array(
    'name' => 'create field_volunteer_interests_roles',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_what_site_you_want'.
  $permissions['create field_what_site_you_want'] = array(
    'name' => 'create field_what_site_you_want',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_app7_statement_agree'.
  $permissions['edit field_app7_statement_agree'] = array(
    'name' => 'edit field_app7_statement_agree',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_app_7_final_agree_1'.
  $permissions['edit field_app_7_final_agree_1'] = array(
    'name' => 'edit field_app_7_final_agree_1',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_app_7_final_agree_2'.
  $permissions['edit field_app_7_final_agree_2'] = array(
    'name' => 'edit field_app_7_final_agree_2',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_app_7_final_agree_3'.
  $permissions['edit field_app_7_final_agree_3'] = array(
    'name' => 'edit field_app_7_final_agree_3',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_app_7_final_agree_4'.
  $permissions['edit field_app_7_final_agree_4'] = array(
    'name' => 'edit field_app_7_final_agree_4',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_app_7_final_agree_5'.
  $permissions['edit field_app_7_final_agree_5'] = array(
    'name' => 'edit field_app_7_final_agree_5',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_app_7_final_agree_6'.
  $permissions['edit field_app_7_final_agree_6'] = array(
    'name' => 'edit field_app_7_final_agree_6',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_app_status'.
  $permissions['edit field_app_status'] = array(
    'name' => 'edit field_app_status',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_app_user'.
  $permissions['edit field_app_user'] = array(
    'name' => 'edit field_app_user',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_beliefs2_q1'.
  $permissions['edit field_beliefs2_q1'] = array(
    'name' => 'edit field_beliefs2_q1',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_beliefs2_q2'.
  $permissions['edit field_beliefs2_q2'] = array(
    'name' => 'edit field_beliefs2_q2',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_beliefs2_q3'.
  $permissions['edit field_beliefs2_q3'] = array(
    'name' => 'edit field_beliefs2_q3',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_beliefs_q1'.
  $permissions['edit field_beliefs_q1'] = array(
    'name' => 'edit field_beliefs_q1',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_beliefs_q2'.
  $permissions['edit field_beliefs_q2'] = array(
    'name' => 'edit field_beliefs_q2',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_beliefs_q3'.
  $permissions['edit field_beliefs_q3'] = array(
    'name' => 'edit field_beliefs_q3',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_beliefs_q4'.
  $permissions['edit field_beliefs_q4'] = array(
    'name' => 'edit field_beliefs_q4',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_beliefs_q5'.
  $permissions['edit field_beliefs_q5'] = array(
    'name' => 'edit field_beliefs_q5',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_beliefs_q6'.
  $permissions['edit field_beliefs_q6'] = array(
    'name' => 'edit field_beliefs_q6',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_beliefs_q7'.
  $permissions['edit field_beliefs_q7'] = array(
    'name' => 'edit field_beliefs_q7',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_church_email'.
  $permissions['edit field_church_email'] = array(
    'name' => 'edit field_church_email',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_church_home'.
  $permissions['edit field_church_home'] = array(
    'name' => 'edit field_church_home',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_church_how_long_attended'.
  $permissions['edit field_church_how_long_attended'] = array(
    'name' => 'edit field_church_how_long_attended',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_church_phone'.
  $permissions['edit field_church_phone'] = array(
    'name' => 'edit field_church_phone',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_church_prev'.
  $permissions['edit field_church_prev'] = array(
    'name' => 'edit field_church_prev',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_church_reference'.
  $permissions['edit field_church_reference'] = array(
    'name' => 'edit field_church_reference',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_color_preference'.
  $permissions['edit field_color_preference'] = array(
    'name' => 'edit field_color_preference',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_completed'.
  $permissions['edit field_completed'] = array(
    'name' => 'edit field_completed',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_email'.
  $permissions['edit field_email'] = array(
    'name' => 'edit field_email',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_empl_length'.
  $permissions['edit field_empl_length'] = array(
    'name' => 'edit field_empl_length',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_empl_title'.
  $permissions['edit field_empl_title'] = array(
    'name' => 'edit field_empl_title',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_employer'.
  $permissions['edit field_employer'] = array(
    'name' => 'edit field_employer',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_expired_date'.
  $permissions['edit field_expired_date'] = array(
    'name' => 'edit field_expired_date',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_faq_a'.
  $permissions['edit field_faq_a'] = array(
    'name' => 'edit field_faq_a',
    'roles' => array(
      'anonymous user' => 'anonymous user',
      'authenticated user' => 'authenticated user',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_how_did_you_hear_about_nov'.
  $permissions['edit field_how_did_you_hear_about_nov'] = array(
    'name' => 'edit field_how_did_you_hear_about_nov',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ministry_cert'.
  $permissions['edit field_ministry_cert'] = array(
    'name' => 'edit field_ministry_cert',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ministry_experience'.
  $permissions['edit field_ministry_experience'] = array(
    'name' => 'edit field_ministry_experience',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_notes'.
  $permissions['edit field_notes'] = array(
    'name' => 'edit field_notes',
    'roles' => array(
      'Reviewer' => 'Reviewer',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_parent_email'.
  $permissions['edit field_parent_email'] = array(
    'name' => 'edit field_parent_email',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_parent_guardian_first_name'.
  $permissions['edit field_parent_guardian_first_name'] = array(
    'name' => 'edit field_parent_guardian_first_name',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_parent_guardian_last_name'.
  $permissions['edit field_parent_guardian_last_name'] = array(
    'name' => 'edit field_parent_guardian_last_name',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_parent_phone'.
  $permissions['edit field_parent_phone'] = array(
    'name' => 'edit field_parent_phone',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_parent_prefix'.
  $permissions['edit field_parent_prefix'] = array(
    'name' => 'edit field_parent_prefix',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_pertinent_q1'.
  $permissions['edit field_pertinent_q1'] = array(
    'name' => 'edit field_pertinent_q1',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_pertinent_q10'.
  $permissions['edit field_pertinent_q10'] = array(
    'name' => 'edit field_pertinent_q10',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_pertinent_q11'.
  $permissions['edit field_pertinent_q11'] = array(
    'name' => 'edit field_pertinent_q11',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_pertinent_q12'.
  $permissions['edit field_pertinent_q12'] = array(
    'name' => 'edit field_pertinent_q12',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_pertinent_q13'.
  $permissions['edit field_pertinent_q13'] = array(
    'name' => 'edit field_pertinent_q13',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_pertinent_q2'.
  $permissions['edit field_pertinent_q2'] = array(
    'name' => 'edit field_pertinent_q2',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_pertinent_q3'.
  $permissions['edit field_pertinent_q3'] = array(
    'name' => 'edit field_pertinent_q3',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_pertinent_q4'.
  $permissions['edit field_pertinent_q4'] = array(
    'name' => 'edit field_pertinent_q4',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_pertinent_q5'.
  $permissions['edit field_pertinent_q5'] = array(
    'name' => 'edit field_pertinent_q5',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_pertinent_q6'.
  $permissions['edit field_pertinent_q6'] = array(
    'name' => 'edit field_pertinent_q6',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_pertinent_q7'.
  $permissions['edit field_pertinent_q7'] = array(
    'name' => 'edit field_pertinent_q7',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_pertinent_q8'.
  $permissions['edit field_pertinent_q8'] = array(
    'name' => 'edit field_pertinent_q8',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_pertinent_q9'.
  $permissions['edit field_pertinent_q9'] = array(
    'name' => 'edit field_pertinent_q9',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_program_policies_agree'.
  $permissions['edit field_program_policies_agree'] = array(
    'name' => 'edit field_program_policies_agree',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_1_email'.
  $permissions['edit field_ref_1_email'] = array(
    'name' => 'edit field_ref_1_email',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_1_first_name'.
  $permissions['edit field_ref_1_first_name'] = array(
    'name' => 'edit field_ref_1_first_name',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_1_how_know'.
  $permissions['edit field_ref_1_how_know'] = array(
    'name' => 'edit field_ref_1_how_know',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_1_how_long'.
  $permissions['edit field_ref_1_how_long'] = array(
    'name' => 'edit field_ref_1_how_long',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_1_how_long_period'.
  $permissions['edit field_ref_1_how_long_period'] = array(
    'name' => 'edit field_ref_1_how_long_period',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_1_last_name'.
  $permissions['edit field_ref_1_last_name'] = array(
    'name' => 'edit field_ref_1_last_name',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_1_phone'.
  $permissions['edit field_ref_1_phone'] = array(
    'name' => 'edit field_ref_1_phone',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_1_prefix'.
  $permissions['edit field_ref_1_prefix'] = array(
    'name' => 'edit field_ref_1_prefix',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_2_email'.
  $permissions['edit field_ref_2_email'] = array(
    'name' => 'edit field_ref_2_email',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_2_first_name'.
  $permissions['edit field_ref_2_first_name'] = array(
    'name' => 'edit field_ref_2_first_name',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_2_how_know'.
  $permissions['edit field_ref_2_how_know'] = array(
    'name' => 'edit field_ref_2_how_know',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_2_how_long'.
  $permissions['edit field_ref_2_how_long'] = array(
    'name' => 'edit field_ref_2_how_long',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_2_how_long_period'.
  $permissions['edit field_ref_2_how_long_period'] = array(
    'name' => 'edit field_ref_2_how_long_period',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_2_last_name'.
  $permissions['edit field_ref_2_last_name'] = array(
    'name' => 'edit field_ref_2_last_name',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_2_phone'.
  $permissions['edit field_ref_2_phone'] = array(
    'name' => 'edit field_ref_2_phone',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_2_prefix'.
  $permissions['edit field_ref_2_prefix'] = array(
    'name' => 'edit field_ref_2_prefix',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_3_email'.
  $permissions['edit field_ref_3_email'] = array(
    'name' => 'edit field_ref_3_email',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_3_first_name'.
  $permissions['edit field_ref_3_first_name'] = array(
    'name' => 'edit field_ref_3_first_name',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_3_how_know'.
  $permissions['edit field_ref_3_how_know'] = array(
    'name' => 'edit field_ref_3_how_know',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_3_how_long'.
  $permissions['edit field_ref_3_how_long'] = array(
    'name' => 'edit field_ref_3_how_long',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_3_how_long_period'.
  $permissions['edit field_ref_3_how_long_period'] = array(
    'name' => 'edit field_ref_3_how_long_period',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_3_last_name'.
  $permissions['edit field_ref_3_last_name'] = array(
    'name' => 'edit field_ref_3_last_name',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_3_phone'.
  $permissions['edit field_ref_3_phone'] = array(
    'name' => 'edit field_ref_3_phone',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ref_3_prefix'.
  $permissions['edit field_ref_3_prefix'] = array(
    'name' => 'edit field_ref_3_prefix',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_reference_request_1'.
  $permissions['edit field_reference_request_1'] = array(
    'name' => 'edit field_reference_request_1',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_reference_request_2'.
  $permissions['edit field_reference_request_2'] = array(
    'name' => 'edit field_reference_request_2',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_reference_request_church'.
  $permissions['edit field_reference_request_church'] = array(
    'name' => 'edit field_reference_request_church',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_reference_request_parents'.
  $permissions['edit field_reference_request_parents'] = array(
    'name' => 'edit field_reference_request_parents',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_reference_request_standby'.
  $permissions['edit field_reference_request_standby'] = array(
    'name' => 'edit field_reference_request_standby',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_ssn'.
  $permissions['edit field_ssn'] = array(
    'name' => 'edit field_ssn',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_texting'.
  $permissions['edit field_texting'] = array(
    'name' => 'edit field_texting',
    'roles' => array(
      'Reviewer' => 'Reviewer',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_things_q1'.
  $permissions['edit field_things_q1'] = array(
    'name' => 'edit field_things_q1',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_things_q2'.
  $permissions['edit field_things_q2'] = array(
    'name' => 'edit field_things_q2',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_things_q3'.
  $permissions['edit field_things_q3'] = array(
    'name' => 'edit field_things_q3',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_things_q4'.
  $permissions['edit field_things_q4'] = array(
    'name' => 'edit field_things_q4',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_things_q5'.
  $permissions['edit field_things_q5'] = array(
    'name' => 'edit field_things_q5',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_things_q6'.
  $permissions['edit field_things_q6'] = array(
    'name' => 'edit field_things_q6',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_volunteer_interests_roles'.
  $permissions['edit field_volunteer_interests_roles'] = array(
    'name' => 'edit field_volunteer_interests_roles',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_what_site_you_want'.
  $permissions['edit field_what_site_you_want'] = array(
    'name' => 'edit field_what_site_you_want',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_app7_statement_agree'.
  $permissions['edit own field_app7_statement_agree'] = array(
    'name' => 'edit own field_app7_statement_agree',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_app_7_final_agree_1'.
  $permissions['edit own field_app_7_final_agree_1'] = array(
    'name' => 'edit own field_app_7_final_agree_1',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_app_7_final_agree_2'.
  $permissions['edit own field_app_7_final_agree_2'] = array(
    'name' => 'edit own field_app_7_final_agree_2',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_app_7_final_agree_3'.
  $permissions['edit own field_app_7_final_agree_3'] = array(
    'name' => 'edit own field_app_7_final_agree_3',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_app_7_final_agree_4'.
  $permissions['edit own field_app_7_final_agree_4'] = array(
    'name' => 'edit own field_app_7_final_agree_4',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_app_7_final_agree_5'.
  $permissions['edit own field_app_7_final_agree_5'] = array(
    'name' => 'edit own field_app_7_final_agree_5',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_app_7_final_agree_6'.
  $permissions['edit own field_app_7_final_agree_6'] = array(
    'name' => 'edit own field_app_7_final_agree_6',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_app_status'.
  $permissions['edit own field_app_status'] = array(
    'name' => 'edit own field_app_status',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_app_user'.
  $permissions['edit own field_app_user'] = array(
    'name' => 'edit own field_app_user',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_beliefs2_q1'.
  $permissions['edit own field_beliefs2_q1'] = array(
    'name' => 'edit own field_beliefs2_q1',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_beliefs2_q2'.
  $permissions['edit own field_beliefs2_q2'] = array(
    'name' => 'edit own field_beliefs2_q2',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_beliefs2_q3'.
  $permissions['edit own field_beliefs2_q3'] = array(
    'name' => 'edit own field_beliefs2_q3',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_beliefs_q1'.
  $permissions['edit own field_beliefs_q1'] = array(
    'name' => 'edit own field_beliefs_q1',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_beliefs_q2'.
  $permissions['edit own field_beliefs_q2'] = array(
    'name' => 'edit own field_beliefs_q2',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_beliefs_q3'.
  $permissions['edit own field_beliefs_q3'] = array(
    'name' => 'edit own field_beliefs_q3',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_beliefs_q4'.
  $permissions['edit own field_beliefs_q4'] = array(
    'name' => 'edit own field_beliefs_q4',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_beliefs_q5'.
  $permissions['edit own field_beliefs_q5'] = array(
    'name' => 'edit own field_beliefs_q5',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_beliefs_q6'.
  $permissions['edit own field_beliefs_q6'] = array(
    'name' => 'edit own field_beliefs_q6',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_beliefs_q7'.
  $permissions['edit own field_beliefs_q7'] = array(
    'name' => 'edit own field_beliefs_q7',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_church_email'.
  $permissions['edit own field_church_email'] = array(
    'name' => 'edit own field_church_email',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_church_home'.
  $permissions['edit own field_church_home'] = array(
    'name' => 'edit own field_church_home',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_church_how_long_attended'.
  $permissions['edit own field_church_how_long_attended'] = array(
    'name' => 'edit own field_church_how_long_attended',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_church_phone'.
  $permissions['edit own field_church_phone'] = array(
    'name' => 'edit own field_church_phone',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_church_prev'.
  $permissions['edit own field_church_prev'] = array(
    'name' => 'edit own field_church_prev',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_church_reference'.
  $permissions['edit own field_church_reference'] = array(
    'name' => 'edit own field_church_reference',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_color_preference'.
  $permissions['edit own field_color_preference'] = array(
    'name' => 'edit own field_color_preference',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_completed'.
  $permissions['edit own field_completed'] = array(
    'name' => 'edit own field_completed',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_email'.
  $permissions['edit own field_email'] = array(
    'name' => 'edit own field_email',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_empl_length'.
  $permissions['edit own field_empl_length'] = array(
    'name' => 'edit own field_empl_length',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_empl_title'.
  $permissions['edit own field_empl_title'] = array(
    'name' => 'edit own field_empl_title',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_employer'.
  $permissions['edit own field_employer'] = array(
    'name' => 'edit own field_employer',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_expired_date'.
  $permissions['edit own field_expired_date'] = array(
    'name' => 'edit own field_expired_date',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_faq_a'.
  $permissions['edit own field_faq_a'] = array(
    'name' => 'edit own field_faq_a',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_how_did_you_hear_about_nov'.
  $permissions['edit own field_how_did_you_hear_about_nov'] = array(
    'name' => 'edit own field_how_did_you_hear_about_nov',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ministry_cert'.
  $permissions['edit own field_ministry_cert'] = array(
    'name' => 'edit own field_ministry_cert',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ministry_experience'.
  $permissions['edit own field_ministry_experience'] = array(
    'name' => 'edit own field_ministry_experience',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_notes'.
  $permissions['edit own field_notes'] = array(
    'name' => 'edit own field_notes',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_parent_email'.
  $permissions['edit own field_parent_email'] = array(
    'name' => 'edit own field_parent_email',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_parent_guardian_first_name'.
  $permissions['edit own field_parent_guardian_first_name'] = array(
    'name' => 'edit own field_parent_guardian_first_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_parent_guardian_last_name'.
  $permissions['edit own field_parent_guardian_last_name'] = array(
    'name' => 'edit own field_parent_guardian_last_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_parent_phone'.
  $permissions['edit own field_parent_phone'] = array(
    'name' => 'edit own field_parent_phone',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_parent_prefix'.
  $permissions['edit own field_parent_prefix'] = array(
    'name' => 'edit own field_parent_prefix',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_pertinent_q1'.
  $permissions['edit own field_pertinent_q1'] = array(
    'name' => 'edit own field_pertinent_q1',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_pertinent_q10'.
  $permissions['edit own field_pertinent_q10'] = array(
    'name' => 'edit own field_pertinent_q10',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_pertinent_q11'.
  $permissions['edit own field_pertinent_q11'] = array(
    'name' => 'edit own field_pertinent_q11',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_pertinent_q12'.
  $permissions['edit own field_pertinent_q12'] = array(
    'name' => 'edit own field_pertinent_q12',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_pertinent_q13'.
  $permissions['edit own field_pertinent_q13'] = array(
    'name' => 'edit own field_pertinent_q13',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_pertinent_q2'.
  $permissions['edit own field_pertinent_q2'] = array(
    'name' => 'edit own field_pertinent_q2',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_pertinent_q3'.
  $permissions['edit own field_pertinent_q3'] = array(
    'name' => 'edit own field_pertinent_q3',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_pertinent_q4'.
  $permissions['edit own field_pertinent_q4'] = array(
    'name' => 'edit own field_pertinent_q4',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_pertinent_q5'.
  $permissions['edit own field_pertinent_q5'] = array(
    'name' => 'edit own field_pertinent_q5',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_pertinent_q6'.
  $permissions['edit own field_pertinent_q6'] = array(
    'name' => 'edit own field_pertinent_q6',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_pertinent_q7'.
  $permissions['edit own field_pertinent_q7'] = array(
    'name' => 'edit own field_pertinent_q7',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_pertinent_q8'.
  $permissions['edit own field_pertinent_q8'] = array(
    'name' => 'edit own field_pertinent_q8',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_pertinent_q9'.
  $permissions['edit own field_pertinent_q9'] = array(
    'name' => 'edit own field_pertinent_q9',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_program_policies_agree'.
  $permissions['edit own field_program_policies_agree'] = array(
    'name' => 'edit own field_program_policies_agree',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_1_email'.
  $permissions['edit own field_ref_1_email'] = array(
    'name' => 'edit own field_ref_1_email',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_1_first_name'.
  $permissions['edit own field_ref_1_first_name'] = array(
    'name' => 'edit own field_ref_1_first_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_1_how_know'.
  $permissions['edit own field_ref_1_how_know'] = array(
    'name' => 'edit own field_ref_1_how_know',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_1_how_long'.
  $permissions['edit own field_ref_1_how_long'] = array(
    'name' => 'edit own field_ref_1_how_long',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_1_how_long_period'.
  $permissions['edit own field_ref_1_how_long_period'] = array(
    'name' => 'edit own field_ref_1_how_long_period',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_1_last_name'.
  $permissions['edit own field_ref_1_last_name'] = array(
    'name' => 'edit own field_ref_1_last_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_1_phone'.
  $permissions['edit own field_ref_1_phone'] = array(
    'name' => 'edit own field_ref_1_phone',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_1_prefix'.
  $permissions['edit own field_ref_1_prefix'] = array(
    'name' => 'edit own field_ref_1_prefix',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_2_email'.
  $permissions['edit own field_ref_2_email'] = array(
    'name' => 'edit own field_ref_2_email',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_2_first_name'.
  $permissions['edit own field_ref_2_first_name'] = array(
    'name' => 'edit own field_ref_2_first_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_2_how_know'.
  $permissions['edit own field_ref_2_how_know'] = array(
    'name' => 'edit own field_ref_2_how_know',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_2_how_long'.
  $permissions['edit own field_ref_2_how_long'] = array(
    'name' => 'edit own field_ref_2_how_long',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_2_how_long_period'.
  $permissions['edit own field_ref_2_how_long_period'] = array(
    'name' => 'edit own field_ref_2_how_long_period',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_2_last_name'.
  $permissions['edit own field_ref_2_last_name'] = array(
    'name' => 'edit own field_ref_2_last_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_2_phone'.
  $permissions['edit own field_ref_2_phone'] = array(
    'name' => 'edit own field_ref_2_phone',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_2_prefix'.
  $permissions['edit own field_ref_2_prefix'] = array(
    'name' => 'edit own field_ref_2_prefix',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_3_email'.
  $permissions['edit own field_ref_3_email'] = array(
    'name' => 'edit own field_ref_3_email',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_3_first_name'.
  $permissions['edit own field_ref_3_first_name'] = array(
    'name' => 'edit own field_ref_3_first_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_3_how_know'.
  $permissions['edit own field_ref_3_how_know'] = array(
    'name' => 'edit own field_ref_3_how_know',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_3_how_long'.
  $permissions['edit own field_ref_3_how_long'] = array(
    'name' => 'edit own field_ref_3_how_long',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_3_how_long_period'.
  $permissions['edit own field_ref_3_how_long_period'] = array(
    'name' => 'edit own field_ref_3_how_long_period',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_3_last_name'.
  $permissions['edit own field_ref_3_last_name'] = array(
    'name' => 'edit own field_ref_3_last_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_3_phone'.
  $permissions['edit own field_ref_3_phone'] = array(
    'name' => 'edit own field_ref_3_phone',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ref_3_prefix'.
  $permissions['edit own field_ref_3_prefix'] = array(
    'name' => 'edit own field_ref_3_prefix',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_reference_request_1'.
  $permissions['edit own field_reference_request_1'] = array(
    'name' => 'edit own field_reference_request_1',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_reference_request_2'.
  $permissions['edit own field_reference_request_2'] = array(
    'name' => 'edit own field_reference_request_2',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_reference_request_church'.
  $permissions['edit own field_reference_request_church'] = array(
    'name' => 'edit own field_reference_request_church',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_reference_request_parents'.
  $permissions['edit own field_reference_request_parents'] = array(
    'name' => 'edit own field_reference_request_parents',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_reference_request_standby'.
  $permissions['edit own field_reference_request_standby'] = array(
    'name' => 'edit own field_reference_request_standby',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_ssn'.
  $permissions['edit own field_ssn'] = array(
    'name' => 'edit own field_ssn',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_texting'.
  $permissions['edit own field_texting'] = array(
    'name' => 'edit own field_texting',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_things_q1'.
  $permissions['edit own field_things_q1'] = array(
    'name' => 'edit own field_things_q1',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_things_q2'.
  $permissions['edit own field_things_q2'] = array(
    'name' => 'edit own field_things_q2',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_things_q3'.
  $permissions['edit own field_things_q3'] = array(
    'name' => 'edit own field_things_q3',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_things_q4'.
  $permissions['edit own field_things_q4'] = array(
    'name' => 'edit own field_things_q4',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_things_q5'.
  $permissions['edit own field_things_q5'] = array(
    'name' => 'edit own field_things_q5',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_things_q6'.
  $permissions['edit own field_things_q6'] = array(
    'name' => 'edit own field_things_q6',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_volunteer_interests_roles'.
  $permissions['edit own field_volunteer_interests_roles'] = array(
    'name' => 'edit own field_volunteer_interests_roles',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_what_site_you_want'.
  $permissions['edit own field_what_site_you_want'] = array(
    'name' => 'edit own field_what_site_you_want',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_app7_statement_agree'.
  $permissions['view field_app7_statement_agree'] = array(
    'name' => 'view field_app7_statement_agree',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_app_7_final_agree_1'.
  $permissions['view field_app_7_final_agree_1'] = array(
    'name' => 'view field_app_7_final_agree_1',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_app_7_final_agree_2'.
  $permissions['view field_app_7_final_agree_2'] = array(
    'name' => 'view field_app_7_final_agree_2',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_app_7_final_agree_3'.
  $permissions['view field_app_7_final_agree_3'] = array(
    'name' => 'view field_app_7_final_agree_3',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_app_7_final_agree_4'.
  $permissions['view field_app_7_final_agree_4'] = array(
    'name' => 'view field_app_7_final_agree_4',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_app_7_final_agree_5'.
  $permissions['view field_app_7_final_agree_5'] = array(
    'name' => 'view field_app_7_final_agree_5',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_app_7_final_agree_6'.
  $permissions['view field_app_7_final_agree_6'] = array(
    'name' => 'view field_app_7_final_agree_6',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_app_status'.
  $permissions['view field_app_status'] = array(
    'name' => 'view field_app_status',
    'roles' => array(
      'Reviewer' => 'Reviewer',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_app_user'.
  $permissions['view field_app_user'] = array(
    'name' => 'view field_app_user',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_beliefs2_q1'.
  $permissions['view field_beliefs2_q1'] = array(
    'name' => 'view field_beliefs2_q1',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_beliefs2_q2'.
  $permissions['view field_beliefs2_q2'] = array(
    'name' => 'view field_beliefs2_q2',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_beliefs2_q3'.
  $permissions['view field_beliefs2_q3'] = array(
    'name' => 'view field_beliefs2_q3',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_beliefs_q1'.
  $permissions['view field_beliefs_q1'] = array(
    'name' => 'view field_beliefs_q1',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_beliefs_q2'.
  $permissions['view field_beliefs_q2'] = array(
    'name' => 'view field_beliefs_q2',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_beliefs_q3'.
  $permissions['view field_beliefs_q3'] = array(
    'name' => 'view field_beliefs_q3',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_beliefs_q4'.
  $permissions['view field_beliefs_q4'] = array(
    'name' => 'view field_beliefs_q4',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_beliefs_q5'.
  $permissions['view field_beliefs_q5'] = array(
    'name' => 'view field_beliefs_q5',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_beliefs_q6'.
  $permissions['view field_beliefs_q6'] = array(
    'name' => 'view field_beliefs_q6',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_beliefs_q7'.
  $permissions['view field_beliefs_q7'] = array(
    'name' => 'view field_beliefs_q7',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_church_email'.
  $permissions['view field_church_email'] = array(
    'name' => 'view field_church_email',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_church_home'.
  $permissions['view field_church_home'] = array(
    'name' => 'view field_church_home',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_church_how_long_attended'.
  $permissions['view field_church_how_long_attended'] = array(
    'name' => 'view field_church_how_long_attended',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_church_phone'.
  $permissions['view field_church_phone'] = array(
    'name' => 'view field_church_phone',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_church_prev'.
  $permissions['view field_church_prev'] = array(
    'name' => 'view field_church_prev',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_church_reference'.
  $permissions['view field_church_reference'] = array(
    'name' => 'view field_church_reference',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_color_preference'.
  $permissions['view field_color_preference'] = array(
    'name' => 'view field_color_preference',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_completed'.
  $permissions['view field_completed'] = array(
    'name' => 'view field_completed',
    'roles' => array(
      'Reviewer' => 'Reviewer',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_email'.
  $permissions['view field_email'] = array(
    'name' => 'view field_email',
    'roles' => array(
      'Reviewer' => 'Reviewer',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_empl_length'.
  $permissions['view field_empl_length'] = array(
    'name' => 'view field_empl_length',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_empl_title'.
  $permissions['view field_empl_title'] = array(
    'name' => 'view field_empl_title',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_employer'.
  $permissions['view field_employer'] = array(
    'name' => 'view field_employer',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_expired_date'.
  $permissions['view field_expired_date'] = array(
    'name' => 'view field_expired_date',
    'roles' => array(
      'Reviewer' => 'Reviewer',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_faq_a'.
  $permissions['view field_faq_a'] = array(
    'name' => 'view field_faq_a',
    'roles' => array(
      'anonymous user' => 'anonymous user',
      'authenticated user' => 'authenticated user',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_how_did_you_hear_about_nov'.
  $permissions['view field_how_did_you_hear_about_nov'] = array(
    'name' => 'view field_how_did_you_hear_about_nov',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ministry_cert'.
  $permissions['view field_ministry_cert'] = array(
    'name' => 'view field_ministry_cert',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ministry_experience'.
  $permissions['view field_ministry_experience'] = array(
    'name' => 'view field_ministry_experience',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_notes'.
  $permissions['view field_notes'] = array(
    'name' => 'view field_notes',
    'roles' => array(
      'Reviewer' => 'Reviewer',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_parent_email'.
  $permissions['view field_parent_email'] = array(
    'name' => 'view field_parent_email',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_parent_guardian_first_name'.
  $permissions['view field_parent_guardian_first_name'] = array(
    'name' => 'view field_parent_guardian_first_name',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_parent_guardian_last_name'.
  $permissions['view field_parent_guardian_last_name'] = array(
    'name' => 'view field_parent_guardian_last_name',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_parent_phone'.
  $permissions['view field_parent_phone'] = array(
    'name' => 'view field_parent_phone',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_parent_prefix'.
  $permissions['view field_parent_prefix'] = array(
    'name' => 'view field_parent_prefix',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_pertinent_q1'.
  $permissions['view field_pertinent_q1'] = array(
    'name' => 'view field_pertinent_q1',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_pertinent_q10'.
  $permissions['view field_pertinent_q10'] = array(
    'name' => 'view field_pertinent_q10',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_pertinent_q11'.
  $permissions['view field_pertinent_q11'] = array(
    'name' => 'view field_pertinent_q11',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_pertinent_q12'.
  $permissions['view field_pertinent_q12'] = array(
    'name' => 'view field_pertinent_q12',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_pertinent_q13'.
  $permissions['view field_pertinent_q13'] = array(
    'name' => 'view field_pertinent_q13',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_pertinent_q2'.
  $permissions['view field_pertinent_q2'] = array(
    'name' => 'view field_pertinent_q2',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_pertinent_q3'.
  $permissions['view field_pertinent_q3'] = array(
    'name' => 'view field_pertinent_q3',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_pertinent_q4'.
  $permissions['view field_pertinent_q4'] = array(
    'name' => 'view field_pertinent_q4',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_pertinent_q5'.
  $permissions['view field_pertinent_q5'] = array(
    'name' => 'view field_pertinent_q5',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_pertinent_q6'.
  $permissions['view field_pertinent_q6'] = array(
    'name' => 'view field_pertinent_q6',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_pertinent_q7'.
  $permissions['view field_pertinent_q7'] = array(
    'name' => 'view field_pertinent_q7',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_pertinent_q8'.
  $permissions['view field_pertinent_q8'] = array(
    'name' => 'view field_pertinent_q8',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_pertinent_q9'.
  $permissions['view field_pertinent_q9'] = array(
    'name' => 'view field_pertinent_q9',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_program_policies_agree'.
  $permissions['view field_program_policies_agree'] = array(
    'name' => 'view field_program_policies_agree',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_1_email'.
  $permissions['view field_ref_1_email'] = array(
    'name' => 'view field_ref_1_email',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_1_first_name'.
  $permissions['view field_ref_1_first_name'] = array(
    'name' => 'view field_ref_1_first_name',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_1_how_know'.
  $permissions['view field_ref_1_how_know'] = array(
    'name' => 'view field_ref_1_how_know',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_1_how_long'.
  $permissions['view field_ref_1_how_long'] = array(
    'name' => 'view field_ref_1_how_long',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_1_how_long_period'.
  $permissions['view field_ref_1_how_long_period'] = array(
    'name' => 'view field_ref_1_how_long_period',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_1_last_name'.
  $permissions['view field_ref_1_last_name'] = array(
    'name' => 'view field_ref_1_last_name',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_1_phone'.
  $permissions['view field_ref_1_phone'] = array(
    'name' => 'view field_ref_1_phone',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_1_prefix'.
  $permissions['view field_ref_1_prefix'] = array(
    'name' => 'view field_ref_1_prefix',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_2_email'.
  $permissions['view field_ref_2_email'] = array(
    'name' => 'view field_ref_2_email',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_2_first_name'.
  $permissions['view field_ref_2_first_name'] = array(
    'name' => 'view field_ref_2_first_name',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_2_how_know'.
  $permissions['view field_ref_2_how_know'] = array(
    'name' => 'view field_ref_2_how_know',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_2_how_long'.
  $permissions['view field_ref_2_how_long'] = array(
    'name' => 'view field_ref_2_how_long',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_2_how_long_period'.
  $permissions['view field_ref_2_how_long_period'] = array(
    'name' => 'view field_ref_2_how_long_period',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_2_last_name'.
  $permissions['view field_ref_2_last_name'] = array(
    'name' => 'view field_ref_2_last_name',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_2_phone'.
  $permissions['view field_ref_2_phone'] = array(
    'name' => 'view field_ref_2_phone',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_2_prefix'.
  $permissions['view field_ref_2_prefix'] = array(
    'name' => 'view field_ref_2_prefix',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_3_email'.
  $permissions['view field_ref_3_email'] = array(
    'name' => 'view field_ref_3_email',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_3_first_name'.
  $permissions['view field_ref_3_first_name'] = array(
    'name' => 'view field_ref_3_first_name',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_3_how_know'.
  $permissions['view field_ref_3_how_know'] = array(
    'name' => 'view field_ref_3_how_know',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_3_how_long'.
  $permissions['view field_ref_3_how_long'] = array(
    'name' => 'view field_ref_3_how_long',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_3_how_long_period'.
  $permissions['view field_ref_3_how_long_period'] = array(
    'name' => 'view field_ref_3_how_long_period',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_3_last_name'.
  $permissions['view field_ref_3_last_name'] = array(
    'name' => 'view field_ref_3_last_name',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_3_phone'.
  $permissions['view field_ref_3_phone'] = array(
    'name' => 'view field_ref_3_phone',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ref_3_prefix'.
  $permissions['view field_ref_3_prefix'] = array(
    'name' => 'view field_ref_3_prefix',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_reference_request_1'.
  $permissions['view field_reference_request_1'] = array(
    'name' => 'view field_reference_request_1',
    'roles' => array(
      'Reviewer' => 'Reviewer',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_reference_request_2'.
  $permissions['view field_reference_request_2'] = array(
    'name' => 'view field_reference_request_2',
    'roles' => array(
      'Reviewer' => 'Reviewer',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_reference_request_church'.
  $permissions['view field_reference_request_church'] = array(
    'name' => 'view field_reference_request_church',
    'roles' => array(
      'Reviewer' => 'Reviewer',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_reference_request_parents'.
  $permissions['view field_reference_request_parents'] = array(
    'name' => 'view field_reference_request_parents',
    'roles' => array(
      'Reviewer' => 'Reviewer',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_reference_request_standby'.
  $permissions['view field_reference_request_standby'] = array(
    'name' => 'view field_reference_request_standby',
    'roles' => array(
      'Reviewer' => 'Reviewer',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_ssn'.
  $permissions['view field_ssn'] = array(
    'name' => 'view field_ssn',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_texting'.
  $permissions['view field_texting'] = array(
    'name' => 'view field_texting',
    'roles' => array(
      'Reviewer' => 'Reviewer',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_things_q1'.
  $permissions['view field_things_q1'] = array(
    'name' => 'view field_things_q1',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_things_q2'.
  $permissions['view field_things_q2'] = array(
    'name' => 'view field_things_q2',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_things_q3'.
  $permissions['view field_things_q3'] = array(
    'name' => 'view field_things_q3',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_things_q4'.
  $permissions['view field_things_q4'] = array(
    'name' => 'view field_things_q4',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_things_q5'.
  $permissions['view field_things_q5'] = array(
    'name' => 'view field_things_q5',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_things_q6'.
  $permissions['view field_things_q6'] = array(
    'name' => 'view field_things_q6',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_volunteer_interests_roles'.
  $permissions['view field_volunteer_interests_roles'] = array(
    'name' => 'view field_volunteer_interests_roles',
    'roles' => array(
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_app7_statement_agree'.
  $permissions['view own field_app7_statement_agree'] = array(
    'name' => 'view own field_app7_statement_agree',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_app_7_final_agree_1'.
  $permissions['view own field_app_7_final_agree_1'] = array(
    'name' => 'view own field_app_7_final_agree_1',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_app_7_final_agree_2'.
  $permissions['view own field_app_7_final_agree_2'] = array(
    'name' => 'view own field_app_7_final_agree_2',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_app_7_final_agree_3'.
  $permissions['view own field_app_7_final_agree_3'] = array(
    'name' => 'view own field_app_7_final_agree_3',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_app_7_final_agree_4'.
  $permissions['view own field_app_7_final_agree_4'] = array(
    'name' => 'view own field_app_7_final_agree_4',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_app_7_final_agree_5'.
  $permissions['view own field_app_7_final_agree_5'] = array(
    'name' => 'view own field_app_7_final_agree_5',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_app_7_final_agree_6'.
  $permissions['view own field_app_7_final_agree_6'] = array(
    'name' => 'view own field_app_7_final_agree_6',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_app_status'.
  $permissions['view own field_app_status'] = array(
    'name' => 'view own field_app_status',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_app_user'.
  $permissions['view own field_app_user'] = array(
    'name' => 'view own field_app_user',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_beliefs2_q1'.
  $permissions['view own field_beliefs2_q1'] = array(
    'name' => 'view own field_beliefs2_q1',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_beliefs2_q2'.
  $permissions['view own field_beliefs2_q2'] = array(
    'name' => 'view own field_beliefs2_q2',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_beliefs2_q3'.
  $permissions['view own field_beliefs2_q3'] = array(
    'name' => 'view own field_beliefs2_q3',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_beliefs_q1'.
  $permissions['view own field_beliefs_q1'] = array(
    'name' => 'view own field_beliefs_q1',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_beliefs_q2'.
  $permissions['view own field_beliefs_q2'] = array(
    'name' => 'view own field_beliefs_q2',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_beliefs_q3'.
  $permissions['view own field_beliefs_q3'] = array(
    'name' => 'view own field_beliefs_q3',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_beliefs_q4'.
  $permissions['view own field_beliefs_q4'] = array(
    'name' => 'view own field_beliefs_q4',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_beliefs_q5'.
  $permissions['view own field_beliefs_q5'] = array(
    'name' => 'view own field_beliefs_q5',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_beliefs_q6'.
  $permissions['view own field_beliefs_q6'] = array(
    'name' => 'view own field_beliefs_q6',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_beliefs_q7'.
  $permissions['view own field_beliefs_q7'] = array(
    'name' => 'view own field_beliefs_q7',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_church_email'.
  $permissions['view own field_church_email'] = array(
    'name' => 'view own field_church_email',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_church_home'.
  $permissions['view own field_church_home'] = array(
    'name' => 'view own field_church_home',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_church_how_long_attended'.
  $permissions['view own field_church_how_long_attended'] = array(
    'name' => 'view own field_church_how_long_attended',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_church_phone'.
  $permissions['view own field_church_phone'] = array(
    'name' => 'view own field_church_phone',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_church_prev'.
  $permissions['view own field_church_prev'] = array(
    'name' => 'view own field_church_prev',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_church_reference'.
  $permissions['view own field_church_reference'] = array(
    'name' => 'view own field_church_reference',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_color_preference'.
  $permissions['view own field_color_preference'] = array(
    'name' => 'view own field_color_preference',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_completed'.
  $permissions['view own field_completed'] = array(
    'name' => 'view own field_completed',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_email'.
  $permissions['view own field_email'] = array(
    'name' => 'view own field_email',
    'roles' => array(
      'Reviewer' => 'Reviewer',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_empl_length'.
  $permissions['view own field_empl_length'] = array(
    'name' => 'view own field_empl_length',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_empl_title'.
  $permissions['view own field_empl_title'] = array(
    'name' => 'view own field_empl_title',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_employer'.
  $permissions['view own field_employer'] = array(
    'name' => 'view own field_employer',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_expired_date'.
  $permissions['view own field_expired_date'] = array(
    'name' => 'view own field_expired_date',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_faq_a'.
  $permissions['view own field_faq_a'] = array(
    'name' => 'view own field_faq_a',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_how_did_you_hear_about_nov'.
  $permissions['view own field_how_did_you_hear_about_nov'] = array(
    'name' => 'view own field_how_did_you_hear_about_nov',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ministry_cert'.
  $permissions['view own field_ministry_cert'] = array(
    'name' => 'view own field_ministry_cert',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ministry_experience'.
  $permissions['view own field_ministry_experience'] = array(
    'name' => 'view own field_ministry_experience',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_notes'.
  $permissions['view own field_notes'] = array(
    'name' => 'view own field_notes',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_parent_email'.
  $permissions['view own field_parent_email'] = array(
    'name' => 'view own field_parent_email',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_parent_guardian_first_name'.
  $permissions['view own field_parent_guardian_first_name'] = array(
    'name' => 'view own field_parent_guardian_first_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_parent_guardian_last_name'.
  $permissions['view own field_parent_guardian_last_name'] = array(
    'name' => 'view own field_parent_guardian_last_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_parent_phone'.
  $permissions['view own field_parent_phone'] = array(
    'name' => 'view own field_parent_phone',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_parent_prefix'.
  $permissions['view own field_parent_prefix'] = array(
    'name' => 'view own field_parent_prefix',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_pertinent_q1'.
  $permissions['view own field_pertinent_q1'] = array(
    'name' => 'view own field_pertinent_q1',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_pertinent_q10'.
  $permissions['view own field_pertinent_q10'] = array(
    'name' => 'view own field_pertinent_q10',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_pertinent_q11'.
  $permissions['view own field_pertinent_q11'] = array(
    'name' => 'view own field_pertinent_q11',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_pertinent_q12'.
  $permissions['view own field_pertinent_q12'] = array(
    'name' => 'view own field_pertinent_q12',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_pertinent_q13'.
  $permissions['view own field_pertinent_q13'] = array(
    'name' => 'view own field_pertinent_q13',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_pertinent_q2'.
  $permissions['view own field_pertinent_q2'] = array(
    'name' => 'view own field_pertinent_q2',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_pertinent_q3'.
  $permissions['view own field_pertinent_q3'] = array(
    'name' => 'view own field_pertinent_q3',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_pertinent_q4'.
  $permissions['view own field_pertinent_q4'] = array(
    'name' => 'view own field_pertinent_q4',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_pertinent_q5'.
  $permissions['view own field_pertinent_q5'] = array(
    'name' => 'view own field_pertinent_q5',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_pertinent_q6'.
  $permissions['view own field_pertinent_q6'] = array(
    'name' => 'view own field_pertinent_q6',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_pertinent_q7'.
  $permissions['view own field_pertinent_q7'] = array(
    'name' => 'view own field_pertinent_q7',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_pertinent_q8'.
  $permissions['view own field_pertinent_q8'] = array(
    'name' => 'view own field_pertinent_q8',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_pertinent_q9'.
  $permissions['view own field_pertinent_q9'] = array(
    'name' => 'view own field_pertinent_q9',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_program_policies_agree'.
  $permissions['view own field_program_policies_agree'] = array(
    'name' => 'view own field_program_policies_agree',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_1_email'.
  $permissions['view own field_ref_1_email'] = array(
    'name' => 'view own field_ref_1_email',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_1_first_name'.
  $permissions['view own field_ref_1_first_name'] = array(
    'name' => 'view own field_ref_1_first_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_1_how_know'.
  $permissions['view own field_ref_1_how_know'] = array(
    'name' => 'view own field_ref_1_how_know',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_1_how_long'.
  $permissions['view own field_ref_1_how_long'] = array(
    'name' => 'view own field_ref_1_how_long',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_1_how_long_period'.
  $permissions['view own field_ref_1_how_long_period'] = array(
    'name' => 'view own field_ref_1_how_long_period',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_1_last_name'.
  $permissions['view own field_ref_1_last_name'] = array(
    'name' => 'view own field_ref_1_last_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_1_phone'.
  $permissions['view own field_ref_1_phone'] = array(
    'name' => 'view own field_ref_1_phone',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_1_prefix'.
  $permissions['view own field_ref_1_prefix'] = array(
    'name' => 'view own field_ref_1_prefix',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_2_email'.
  $permissions['view own field_ref_2_email'] = array(
    'name' => 'view own field_ref_2_email',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_2_first_name'.
  $permissions['view own field_ref_2_first_name'] = array(
    'name' => 'view own field_ref_2_first_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_2_how_know'.
  $permissions['view own field_ref_2_how_know'] = array(
    'name' => 'view own field_ref_2_how_know',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_2_how_long'.
  $permissions['view own field_ref_2_how_long'] = array(
    'name' => 'view own field_ref_2_how_long',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_2_how_long_period'.
  $permissions['view own field_ref_2_how_long_period'] = array(
    'name' => 'view own field_ref_2_how_long_period',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_2_last_name'.
  $permissions['view own field_ref_2_last_name'] = array(
    'name' => 'view own field_ref_2_last_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_2_phone'.
  $permissions['view own field_ref_2_phone'] = array(
    'name' => 'view own field_ref_2_phone',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_2_prefix'.
  $permissions['view own field_ref_2_prefix'] = array(
    'name' => 'view own field_ref_2_prefix',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_3_email'.
  $permissions['view own field_ref_3_email'] = array(
    'name' => 'view own field_ref_3_email',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_3_first_name'.
  $permissions['view own field_ref_3_first_name'] = array(
    'name' => 'view own field_ref_3_first_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_3_how_know'.
  $permissions['view own field_ref_3_how_know'] = array(
    'name' => 'view own field_ref_3_how_know',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_3_how_long'.
  $permissions['view own field_ref_3_how_long'] = array(
    'name' => 'view own field_ref_3_how_long',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_3_how_long_period'.
  $permissions['view own field_ref_3_how_long_period'] = array(
    'name' => 'view own field_ref_3_how_long_period',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_3_last_name'.
  $permissions['view own field_ref_3_last_name'] = array(
    'name' => 'view own field_ref_3_last_name',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_3_phone'.
  $permissions['view own field_ref_3_phone'] = array(
    'name' => 'view own field_ref_3_phone',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ref_3_prefix'.
  $permissions['view own field_ref_3_prefix'] = array(
    'name' => 'view own field_ref_3_prefix',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_reference_request_1'.
  $permissions['view own field_reference_request_1'] = array(
    'name' => 'view own field_reference_request_1',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_reference_request_2'.
  $permissions['view own field_reference_request_2'] = array(
    'name' => 'view own field_reference_request_2',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_reference_request_church'.
  $permissions['view own field_reference_request_church'] = array(
    'name' => 'view own field_reference_request_church',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_reference_request_parents'.
  $permissions['view own field_reference_request_parents'] = array(
    'name' => 'view own field_reference_request_parents',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_reference_request_standby'.
  $permissions['view own field_reference_request_standby'] = array(
    'name' => 'view own field_reference_request_standby',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_ssn'.
  $permissions['view own field_ssn'] = array(
    'name' => 'view own field_ssn',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_texting'.
  $permissions['view own field_texting'] = array(
    'name' => 'view own field_texting',
    'roles' => array(),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_things_q1'.
  $permissions['view own field_things_q1'] = array(
    'name' => 'view own field_things_q1',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_things_q2'.
  $permissions['view own field_things_q2'] = array(
    'name' => 'view own field_things_q2',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_things_q3'.
  $permissions['view own field_things_q3'] = array(
    'name' => 'view own field_things_q3',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_things_q4'.
  $permissions['view own field_things_q4'] = array(
    'name' => 'view own field_things_q4',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_things_q5'.
  $permissions['view own field_things_q5'] = array(
    'name' => 'view own field_things_q5',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_things_q6'.
  $permissions['view own field_things_q6'] = array(
    'name' => 'view own field_things_q6',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_volunteer_interests_roles'.
  $permissions['view own field_volunteer_interests_roles'] = array(
    'name' => 'view own field_volunteer_interests_roles',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_what_site_you_want'.
  $permissions['view own field_what_site_you_want'] = array(
    'name' => 'view own field_what_site_you_want',
    'roles' => array(
      'Applicant US citizen' => 'Applicant US citizen',
      'Siteadmin' => 'Siteadmin',
    ),
    'module' => 'field_permissions',
  );

  return $permissions;
}
