<?php

/** Constants */
define('NOVO_VOCABULARY_STATES', 'states');
define('NOVO_VOCABULARY_GENDER', 'gender');

/**
 * Implements hook_taxonomy_vocabulary_insert().
 */
function novo_taxonomy_feature_taxonomy_vocabulary_insert($vocabulary) {

  if ($vocabulary->machine_name == NOVO_VOCABULARY_STATES) {
    //lets import known states
    $state_list = array(
      'AL' => "Alabama",
      'AK' => "Alaska",
      'AZ' => "Arizona",
      'AR' => "Arkansas",
      'CA' => "California",
      'CO' => "Colorado",
      'CT' => "Connecticut",
      'DE' => "Delaware",
      'DC' => "District Of Columbia",
      'FL' => "Florida",
      'GA' => "Georgia",
      'HI' => "Hawaii",
      'ID' => "Idaho",
      'IL' => "Illinois",
      'IN' => "Indiana",
      'IA' => "Iowa",
      'KS' => "Kansas",
      'KY' => "Kentucky",
      'LA' => "Louisiana",
      'ME' => "Maine",
      'MD' => "Maryland",
      'MA' => "Massachusetts",
      'MI' => "Michigan",
      'MN' => "Minnesota",
      'MS' => "Mississippi",
      'MO' => "Missouri",
      'MT' => "Montana",
      'NE' => "Nebraska",
      'NV' => "Nevada",
      'NH' => "New Hampshire",
      'NJ' => "New Jersey",
      'NM' => "New Mexico",
      'NY' => "New York",
      'NC' => "North Carolina",
      'ND' => "North Dakota",
      'OH' => "Ohio",
      'OK' => "Oklahoma",
      'OR' => "Oregon",
      'PA' => "Pennsylvania",
      'RI' => "Rhode Island",
      'SC' => "South Carolina",
      'SD' => "South Dakota",
      'TN' => "Tennessee",
      'TX' => "Texas",
      'UT' => "Utah",
      'VT' => "Vermont",
      'VA' => "Virginia",
      'WA' => "Washington",
      'WV' => "West Virginia",
      'WI' => "Wisconsin",
      'WY' => "Wyoming"
    );
    foreach ($state_list as $abbr => $state_name) {
      $term = new stdClass();
      $term->name = $state_name;
      $term->description = $abbr;
      $term->vid = $vocabulary->vid;
      taxonomy_term_save($term);
    }
  }

  if ($vocabulary->machine_name == NOVO_VOCABULARY_GENDER) {
    $list = array(
      'M' => "Male",
      'F' => "Female",
    );
    foreach ($list as $abbr => $name) {
      $term = new stdClass();
      $term->name = $abbr;
      $term->description = $name;
      $term->vid = $vocabulary->vid;
      taxonomy_term_save($term);
    }
  }
}
