<?php

/**
 * @file
 * Mail templates.
 */

module_load_include("inc", "novo_mail", "includes/novo_mail.func");
module_load_include("inc", "novo_mail", "includes/novo_mail.cron");

define("NOVO_MAIL_BASE_EMAIL_FOR_REPLACE_TEMPLATE", "volunteer@novoministries.org");

define("NOVO_MAIL_EMAILS", serialize([
  // Application emails.
  [
    'key' => 'novo_mail_app_expired_to_admin',
    'template' => 'templates/email/application/expiration/novo-mail-app-expired-to-admin',
    'subject' => 'Background Check Expired!',
    'is_manager' => TRUE,
  ],
  [
    'key' => 'novo_mail_app_expired_to_volunteer',
    'template' => 'templates/email/application/expiration/novo-mail-app-expired-to-volunteer',
    'subject' => 'Novoministries background check expired!',
  ],
  [
    'key' => 'novo_mail_app_approved_to_volunteer',
    'template' => 'templates/email/application/novo-mail-app-approved-to-volunteer',
    'subject' => 'You\'re Approved',
  ],
  [
    'key' => 'novo_mail_app_approved_to_admin',
    'template' => 'templates/email/application/novo-mail-app-approved-to-admin',
    'subject' => 'Application Approved, need a call',
    'is_manager' => TRUE,
  ],
  [
    'key' => 'novo_mail_app_not_approved_to_admin',
    'template' => 'templates/email/application/novo-mail-app-not-approved-to-admin',
    'subject' => 'Application Not Approved, need a call',
    'is_manager' => TRUE,
  ],
  [
    'key' => 'novo_mail_app_submitted_to_volunteer',
    'template' => 'templates/email/application/novo-mail-app-submitted-to-volunteer',
    'subject' => 'Application Submitted',
  ],
  [
    'key' => 'novo_mail_app_submitted_to_admin',
    'template' => 'templates/email/application/novo-mail-app-submitted-to-admin',
    'subject' => 'New Application Submitted - app_first_name app_last_name',
    'is_manager' => TRUE,
  ],

  [
    'key' => 'novo_mail_app_not_completed_to_admin_24',
    'template' => 'templates/email/application/novo-mail-app-not-completed-to-admin-24',
    'subject' => 'Application Incomplete - 24 Hour Notice',
    'is_manager' => TRUE,
  ],
  [
    'key' => 'novo_mail_app_not_completed_to_admin_72',
    'template' => 'templates/email/application/novo-mail-app-not-completed-to-admin-72',
    'subject' => 'Application Incomplete - 72 Hour Notice',
    'is_manager' => TRUE,
  ],

  [
    'key' => 'novo_mail_app_not_completed_to_volunteer_24',
    'template' => 'templates/email/application/novo-mail-app-not-completed-to-volunteer-24',
    'subject' => 'Let\'s Get You Connected!',
  ],

  [
    'key' => 'novo_mail_app_exp_app_checked_by_applicant_to_admin',
    'template' => 'templates/email/application/expiration/novo-mail-app-exp-app-checked-by-applicant-to-admin',
    'subject' => 'Expired application checked by applicant',
    'is_manager' => TRUE,
  ],

  [
    'key' => 'novo_mail_app_becoming_of_age_to_admin',
    'template' => 'templates/email/application/novo-mail-app-becoming-of-age-to-admin',
    'subject' => 'Active Volunteer app_first_name app_last_name Turning 18',
    'is_manager' => TRUE,
  ],

  // References/requests to admins.
  [
    'key' => 'novo_mail_ref_finished_form_to_admin',
    'template' => 'templates/email/requests/novo-mail-ref-finished-form-to-admin',
    'subject' => 'app_first_name app_last_name Personal References Completed (Both).',
    'is_manager' => TRUE,
  ],
  [
    'key' => 'novo_mail_church_finished_form_to_admin',
    'template' => 'templates/email/requests/novo-mail-church-finished-form-to-admin',
    'subject' => 'app_first_name app_last_name Church Reference Completed.',
    'is_manager' => TRUE,
  ],
  [
    'key' => 'novo_mail_parent_finished_form_to_admin',
    'template' => 'templates/email/requests/novo-mail-parent-finished-form-to-admin',
    'subject' => 'app_first_name app_last_name Parental Approval Form Completed.',
    'is_manager' => TRUE,
  ],

  // References/requests to refs.
  [
    'key' => 'novo_mail_ref_form_to_parent',
    'template' => 'templates/email/requests/novo-mail-ref-form-to-parent',
    'subject' => 'app_first_name app_last_name Has Applied to Volunteer.',
  ],
  [
    'key' => 'novo_mail_ref_form_to_reference',
    'template' => 'templates/email/requests/novo-mail-ref-form-to-reference',
    'subject' => 'app_first_name app_last_name Has Requested You As a Reference!',
  ],
  [
    'key' => 'novo_mail_ref_form_to_church',
    'template' => 'templates/email/requests/novo-mail-ref-form-to-church',
    'subject' => 'app_first_name app_last_name Has Requested You As a Church Reference!',
  ],

  [
    'key' => 'novo_mail_ref_without_email_to_admin',
    'template' => 'templates/email/requests/novo-mail-ref-without-email-to-admin',
    'subject' => 'References without email.',
    'is_manager' => TRUE,
  ],


]));

/**
 * Implements hook_menu().
 */
function novo_mail_menu() {
  $items = array();

  $items['novo-mail/test'] = array(
    'title' => 'novo_mail_test',
    'page callback' => 'novo_mail_test',
    'page arguments' => array(),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

// @codingStandardsIgnoreStart
function novo_mail_test() {
  // Not completed nids.
//  $email_queue = DrupalQueue::get('novo_mail_app_exp_email_queue');
//  $data = novo_mail_app_get_all_expired_nids();
//  kpr($data);
//  foreach ($data as $key => $item) {
//    $email_queue->createItem((array) $item);
//  }

  //novo_mail_add_status_to_storage('novo_mail_app_expired_to_admin', 14450);

  //include_once("/Users/svipsa/Dev/Sites/DBNovoministries/docroot/sites/all/modules/custom/novo_migrate/includes/volunteerNovoMigration.inc");

//  $vm = new VolunteerNovoMigration();
//
//  $r = $vm->getReferenceRequests();
//  kpr($r);

  return "";
}
// @codingStandardsIgnoreEnd

/**
 * Implements hook_theme().
 */
function novo_mail_theme() {
  $emails_conf = unserialize(NOVO_MAIL_EMAILS);
  $themes = [];
  foreach ($emails_conf as $item) {
    $themes[$item['key']] = [
      'variables' => ['params' => NULL],
      'template' => $item['template'],
    ];
  }

  return $themes;
}

/**
 * Implements hook_mail().
 */
function novo_mail_mail($key, &$message, $params) {
  $message['headers']['MIME-Version'] = '1.0';
  $message['headers']['Content-Type'] = 'multipart/mixed;';
  $message['headers']['Content-Type'] = 'text/html;';
  $message['from'] = NOVO_MASTER_BASE_EMAIL;

  $emails_conf = unserialize(NOVO_MAIL_EMAILS);
  foreach ($emails_conf as $item) {
    if ($item['key'] == $key) {
      $message['subject'] = strip_tags(t($item['subject'], $params));
      $message['body'][] = theme($item['key'], ['params' => $params]);
    }
  }
}

/**
 * Email: application was approved (Admin click bu button).
 */
function novo_mail_app_approved($nid) {
  novo_mail_add_to_queue($nid, 'novo_mail_app_approved_to_volunteer');
}

/**
 * Email: To Manager, Application Approved, need a call.
 */
function novo_mail_app_admin_approved($nid) {
  novo_mail_add_to_queue($nid, 'novo_mail_app_approved_to_admin');
}

/**
 * Email: To Manager, Application Not Approved, need a call.
 */
function novo_mail_app_admin_not_approved($nid) {
  novo_mail_add_to_queue($nid, 'novo_mail_app_not_approved_to_admin');
}

/**
 * Email: application was submitted.
 */
function novo_mail_app_submitted($nid) {
  novo_mail_add_to_queue($nid, 'novo_mail_app_submitted_to_volunteer');
  novo_mail_add_to_queue($nid, 'novo_mail_app_submitted_to_admin');
}

/**
 * Email: Notify user about expiration.
 */
function novo_mail_app_notify_user_exp($nid) {
  $additional_params = ['link' => url("node/" . $nid . "/edit", ["absolute" => TRUE])];
  novo_mail_add_to_queue($nid, 'novo_mail_app_expired_to_volunteer', $additional_params);
}

/**
 * Email: To Manager, Expired application checked by applicant.
 */
function novo_mail_app_exp_app_checked_by_applicant_to_admin($nid) {
  novo_mail_add_to_queue($nid, 'novo_mail_app_exp_app_checked_by_applicant_to_admin');
}

/**
 * Email: References have finished forms (both).
 */
function novo_mail_ref_form_finished($app_nid) {
  novo_mail_add_to_queue($app_nid, 'novo_mail_ref_finished_form_to_admin');
}

/**
 * Email: Church have finished form.
 */
function novo_mail_church_form_finished($app_nid) {
  novo_mail_add_to_queue($app_nid, 'novo_mail_church_finished_form_to_admin');
}

/**
 * Email: Parent have finished form.
 */
function novo_mail_parent_form_finished($app_nid) {
  novo_mail_add_to_queue($app_nid, 'novo_mail_parent_finished_form_to_admin');
}

/**
 * Email: To Church, To Ref, To Parent base email.
 */
function novo_mail_ref_form_to_base($key, $app_nid, $ref_nid) {
  $task_data = novo_ref_request_task_get_last($ref_nid);
  if (!empty($task_data)) {
    $additional_params = [
      'ref_name' => $task_data->ref_name,
      'callback' => 'novo_ref_request_task_update_status_by_id',
      'callback_params' => [$task_data->id, 1],
    ];

    if (isset($task_data->email) && $task_data->email == NOVO_MAIL_BASE_EMAIL_FOR_REPLACE_TEMPLATE) {
      // Redirect to managers.
      $additional_params['link'] = url("node/" . $app_nid . "/edit", ["absolute" => TRUE]);
      novo_mail_add_to_queue($app_nid, 'novo_mail_ref_without_email_to_admin', $additional_params);
    }
    else {
      $additional_params['link'] = novo_ref_request_generate_hashed_link($ref_nid);
      $additional_params['email_to'] = $task_data->email;
      novo_mail_add_to_queue($app_nid, $key, $additional_params);
    }
  }
}

/**
 * Email: To Reference, Applicant reference request.
 */
function novo_mail_ref_form_to_reference($app_nid, $ref_nid) {
  novo_mail_ref_form_to_base('novo_mail_ref_form_to_reference', $app_nid, $ref_nid);
}

/**
 * Email: To Parent, Applicant want to volunteer.
 */
function novo_mail_ref_form_to_parent($app_nid, $ref_nid) {
  novo_mail_ref_form_to_base('novo_mail_ref_form_to_parent', $app_nid, $ref_nid);
}

/**
 * Email: To Church, Applicant reference request.
 */
function novo_mail_ref_form_to_church($app_nid, $ref_nid) {
  novo_mail_ref_form_to_base('novo_mail_ref_form_to_church', $app_nid, $ref_nid);
}
