<?php

/**
 * @file
 * Mail templates.
 */

module_load_include("inc", "novo_mail", "includes/novo_mail.func");
module_load_include("inc", "novo_mail", "includes/novo_mail.cron");


define("NOVO_MAIL_EMAILS", serialize([
  [
    'key' => 'novo_mail_app_expired_to_admin',
    'template' => 'templates/email/application/expiration/novo-mail-app-expired-to-admin',
    'theme' => 'novo_mail_app_expired_to_admin',
    'subject' => 'Background Check Expired!',
    'is_manager' => TRUE,
  ],
  [
    'key' => 'novo_mail_app_expired_to_volunteer',
    'template' => 'templates/email/application/expiration/novo-mail-app-expired-to-volunteer',
    'theme' => 'novo_mail_app_expired_to_volunteer',
    'subject' => 'Novoministries background check expired!',
  ],
  [
    'key' => 'novo_mail_app_approved_to_volunteer',
    'template' => 'templates/email/application/novo-mail-app-approved-to-volunteer',
    'theme' => 'novo_mail_app_approved_to_volunteer',
    'subject' => 'You\'re Approved',
  ],
  [
    'key' => 'novo_mail_app_approved_to_admin',
    'template' => 'templates/email/application/novo-mail-app-approved-to-admin',
    'theme' => 'novo_mail_app_approved_to_admin',
    'subject' => 'Application Approved, need a call',
    'is_manager' => TRUE,
  ],
  [
    'key' => 'novo_mail_app_not_approved_to_admin',
    'template' => 'templates/email/application/novo-mail-app-not-approved-to-admin',
    'theme' => 'novo_mail_app_not_approved_to_admin',
    'subject' => 'Application Not Approved, need a call',
    'is_manager' => TRUE,
  ],
  [
    'key' => 'novo_mail_app_submitted_to_volunteer',
    'template' => 'templates/email/application/novo-mail-app-submitted-to-volunteer',
    'theme' => 'novo_mail_app_submitted_to_volunteer',
    'subject' => 'Application Submitted',
  ],
  [
    'key' => 'novo_mail_app_submitted_to_admin',
    'template' => 'templates/email/application/novo-mail-app-submitted-to-admin',
    'theme' => 'novo_mail_app_submitted_to_admin',
    'subject' => 'New Application Submitted - app_first_name app_last_name',
    'is_manager' => TRUE,
  ],

  [
    'key' => 'novo_mail_app_not_completed_to_admin_24',
    'template' => 'templates/email/application/novo-mail-app-not-completed-to-admin-24',
    'theme' => 'novo_mail_app_not_completed_to_admin_24',
    'subject' => 'Application Incomplete - 24 Hour Notice',
    'is_manager' => TRUE,
  ],
  [
    'key' => 'novo_mail_app_not_completed_to_admin_72',
    'template' => 'templates/email/application/novo-mail-app-not-completed-to-admin-72',
    'theme' => 'novo_mail_app_not_completed_to_admin_72',
    'subject' => 'Application Incomplete - 72 Hour Notice',
    'is_manager' => TRUE,
  ],

  [
    'key' => 'novo_mail_app_not_completed_to_volunteer_24',
    'template' => 'templates/email/application/novo-mail-app-not-completed-to-volunteer-24',
    'theme' => 'novo_mail_app_not_completed_to_volunteer_24',
    'subject' => 'Let\'s Get You Connected!',
  ],



]));

/**
 * Implements hook_menu().
 */
function novo_mail_menu() {
  $items = array();

  $items['novo-mail/test'] = array(
    'title' => 'novo_mail_test',
    'page callback' => 'novo_mail_test',
    'page arguments' => array(),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );

  return $items;
}

function novo_mail_test() {
  // Not completed nids.
//  $email_queue = DrupalQueue::get('novo_mail_app_exp_email_queue');
//  $data = novo_mail_app_get_all_expired_nids();
//  kpr($data);
//  foreach ($data as $key => $item) {
//    $email_queue->createItem((array) $item);
//  }

  //novo_mail_add_status_to_storage('novo_mail_app_expired_to_admin', 14450);

  return "";
}

/**
 * Implements hook_theme().
 */
function novo_mail_theme() {
  $emails_conf = unserialize(NOVO_MAIL_EMAILS);
  $themes = [];
  foreach ($emails_conf as $item) {
    $themes[$item['key']] = [
      'variables' => ['params' => NULL],
      'template' => $item['template'],
    ];
  }

  return $themes;
}

/**
 * Implements hook_mail().
 */
function novo_mail_mail($key, &$message, $params) {
  $message['headers']['MIME-Version'] = '1.0';
  $message['headers']['Content-Type'] = 'multipart/mixed;';
  $message['headers']['Content-Type'] = 'text/html;';
  $message['from'] = NOVO_MASTER_BASE_EMAIL;

  $emails_conf = unserialize(NOVO_MAIL_EMAILS);
  foreach ($emails_conf as $item) {
    if ($item['key'] == $key) {
      $message['subject'] = strip_tags(t($item['subject'], $params));
      $message['body'][] = theme($item['theme'], ['params' => $params]);
    }
  }
}

/**
 * Email: application was approved (Admin click bu button).
 */
function novo_mail_app_approved($nid) {
  novo_mail_add_to_queue($nid, 'novo_mail_app_approved_to_volunteer');
}

/**
 * Email: CIA application was approved. @TODO: add to CIA
 */
function novo_mail_app_cia_approved($nid) {
  novo_mail_add_to_queue($nid, 'novo_mail_app_approved_to_admin');
}

/**
 * Email: CIA application was not approved. @TODO: add to CIA
 */
function novo_mail_app_cia_not_approved($nid) {
  novo_mail_add_to_queue($nid, 'novo_mail_app_not_approved_to_admin');
}

/**
 * Email: application was submitted.
 */
function novo_mail_app_submitted($nid) {
  novo_mail_add_to_queue($nid, 'novo_mail_app_submitted_to_volunteer');
  novo_mail_add_to_queue($nid, 'novo_mail_app_submitted_to_admin');
}


/**
 * Email: Notify user about expiration.
 */
function novo_mail_app_notify_user_exp($nid) {
  $additional_params = ['link' => url("node/" . $nid . "/edit", ["absolute" => TRUE])];
  novo_mail_add_to_queue($nid, 'novo_mail_app_expired_to_volunteer', $additional_params);
}

