<?php

/**
 * @file
 * Helper functions.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function novo_attendance_form_attendance_node_form_alter(&$form, &$form_state, $form_id) {
  $form['#attached']['js'][] = drupal_get_path("module", "novo_attendance") . "/js/novo_attendance.js";
  $form['field_attendance_date'][LANGUAGE_NONE]['#element_validate'][] = 'novo_attendance_field_attendance_date_validate';

  // Fix by https://www.drupal.org/node/2842043.
  $year_copy = $form['field_attendance_year'];
  $location_copy = $form['field_attendance_location'];
  $program_copy = $form['field_attendance_program_name'];
  $kids_copy = $form['field_attendance_kids_list'];

  unset($form['field_attendance_year']);
  unset($form['field_attendance_location']);
  unset($form['field_attendance_program_name']);
  unset($form['field_attendance_kids_list']);
  $form['field_attendance_year'] = $year_copy;
  $form['field_attendance_location'] = $location_copy;
  $form['field_attendance_program_name'] = $program_copy;
  $form['field_attendance_kids_list'] = $kids_copy;

  $form['field_attendance_staff_list']['#attributes']['class'] = ['chosen-widget'];
  $form['field_attendance_volunteer_list']['#attributes']['class'] = ['chosen-widget'];

  $form['field_attendance_staff_list'][LANGUAGE_NONE]['#attributes']['class'] = ['chosen-widget'];
  $form['field_attendance_volunteer_list'][LANGUAGE_NONE]['#attributes']['class'] = ['chosen-widget'];

  // Disable change date field on edit form.
  $is_new = (isset($form['nid']['#value']) && !empty($form['nid']['#value'])) ? FALSE : TRUE;
  if (!$is_new) {
    $form['field_attendance_date'][$form['field_attendance_date']['#language']]['#disabled'] = TRUE;
  }

  $form['field_attendance_program_name'][$form['field_attendance_program_name']['#language']]['#suffix'] = t("If no options add !link first", ["!link" => l(t("Enrolment"), "node/add/program", ['query' => drupal_get_destination()])]);
}

/**
 * Attendance date validate.
 */
function novo_attendance_field_attendance_date_validate($element, &$form_state, $form) {
  $values = isset($form_state['values']) ? $form_state['values'] : [];

  $year = isset($values['field_attendance_year'][LANGUAGE_NONE]) ? $values['field_attendance_year'][LANGUAGE_NONE] : NULL;
  $date = (isset($element[0]['#value']['value']['date'])) ? $element[0]['#value']['value']['date'] : NULL;

  if (!$date) {
    form_error($element, t('Date is not valid.'));
  }
  $unix_date = strtotime($date);
  // Set end of day.
  $unix_date += 23 * 59 * 59;

  $date_year = date("Y", $unix_date);

  if ($date_year != $year && $date_year - 1 != $year) {
    form_error($element, t('Date is not valid.'));
  }

  $program_nid = isset($values['field_attendance_program_name'][$values['language']]) ? $values['field_attendance_program_name'][$values['language']] : NULL;
  $program = node_load($program_nid);
  if (isset($program->created)) {
    if ($program->created > $unix_date) {
      form_error($element, t('Date must be greater than the date of creation of the enrollment. (:date)', [":date" => format_date($program->created, 'short')]));
    }
  }
  else {
    form_error($element, t('Date is not valid.'));
  }
}
