<?php

/**
 * @file
 * Helper functions.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function novo_attendance_form_attendance_node_form_alter(&$form, &$form_state, $form_id) {
  $form['#attached']['js'][] = drupal_get_path("module", "novo_attendance") . "/js/novo_attendance.js";
  $form['field_attendance_date'][LANGUAGE_NONE]['#element_validate'][] = 'novo_attendance_field_attendance_date_validate';

  // Fix by https://www.drupal.org/node/2842043.
  $year_copy = $form['field_attendance_year'];
  $program_copy = $form['field_attendance_program_name'];
  $kids_copy = $form['field_attendance_kids_list'];
  unset($form['field_attendance_year']);
  unset($form['field_attendance_program_name']);
  unset($form['field_attendance_kids_list']);
  $form['field_attendance_year'] = $year_copy;
  $form['field_attendance_program_name'] = $program_copy;
  $form['field_attendance_kids_list'] = $kids_copy;

  $form['field_attendance_staff_list']['#attributes']['class'] = array('chosen-widget');
  $form['field_attendance_volunteer_list']['#attributes']['class'] = array('chosen-widget');

  $form['field_attendance_staff_list'][LANGUAGE_NONE]['#attributes']['class'] = array('chosen-widget');
  $form['field_attendance_volunteer_list'][LANGUAGE_NONE]['#attributes']['class'] = array('chosen-widget');
}

/**
 * Attendance date validate.
 */
function novo_attendance_field_attendance_date_validate($element, &$form_state, $form) {
  $values = isset($form_state['values']) ? $form_state['values'] : array();

  $year = isset($values['field_attendance_year'][LANGUAGE_NONE][0]['value']['year']) ? $values['field_attendance_year'][LANGUAGE_NONE][0]['value']['year'] : NULL;
  $date = (isset($element[0]['#value']['value']['date'])) ? $element[0]['#value']['value']['date'] : NULL;

  if (!$date) {
    form_error($element, t('Date is not valid.'));
  }

  $date_year = date("Y", strtotime($date));

  if ($date_year != $year && $date_year - 1 != $year) {
    form_error($element, t('Date is not valid.'));
  }
}
