<?php

/**
 * @file
 * Helper functions.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function novo_program_form_program_node_form_alter(&$form, &$form_state, $form_id) {

}

/**
 * Implements hook_preprocess_field().
 */
function novo_program_preprocess_field($variables) {

}

/**
 * Implements hook_preprocess_node().
 */
function novo_program_preprocess_node($variables) {
  if (isset($variables['node']) && isset($variables['view_mode']) && $variables['view_mode'] == "full" && $variables['type'] == 'program' && node_access("update", $variables['node'])) {
    drupal_goto("node/" . $variables['nid'] . "/edit");
  }
}
